### PR TITLE
Scrapes running in EKS fail after first scrape

### PR DESCRIPTION
**Pull request by rrusso1982**
When the call to get `GetCallerIdentity` is performed outside the metrics scrape functions we can get into the situation where the lookup fails due to token expiration when an inline assume role has been performed.  This most prominently occurs when using a service account assumption from within an EKS cluster.

To alleviate this problem this moves the sts calls within the scraping functions so they are performed in just in time for the accountid to be used as part of the lookups.  

This should be the resolution for #347

### CODE REVIEW

**Comment by Anta-Krumina** [comment]
This PR solves our problem when starting up yace. Thanks @rrusso1982 !
Waiting when this is going to be merged in master and ready to use.

**Comment by thomaspeitz** [comment]
Please rebase and I merge and release as fast as possible. Thanks for the fix :)

**Comment by haarchri** [comment]
when we can see the fix in a release ? ;)

**Comment by rrusso1982** [comment]
> Please rebase and I merge and release as fast as possible. Thanks for the fix :)

rebase complete!

**Comment by haarchri** [comment]
we build up a image from master - but it looks like the exporter hangs after first scrape without a message 

```
{"level":"debug","msg":"Metrics scraped.","time":"2021-04-15T14:18:22Z"}
{"level":"debug","msg":"Sleeping at regular sleep interval 172800","time":"2021-04-15T14:18:22Z"}
```

no more message come up since 2 hours 
any ideas ?

**Pull request merged**
