### PR TITLE
Upgrade to aws-sdk-go-v2

### PR DESCRIPTION
**Pull request by lbenedetto**
Also upgrade Go to 1.14

Not yet tested, but it does at least compile and start-up locally.

### CODE REVIEW

**Comment by lbenedetto** [comment]
I've begun testing this, and I definitely have some more work to do. There is a segfault after startup.

```panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x758b4f]
goroutine 20 [running]:
github.com/aws/aws-sdk-go-v2/aws.New(0xc000028670, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/aws/aws-sdk-go-v2@v0.20.0/aws/request.go:213 +0x46f
github.com/aws/aws-sdk-go-v2/aws.(*Client).NewRequest(...)
	/go/pkg/mod/github.com/aws/aws-sdk-go-v2@v0.20.0/aws/client.go:63
github.com/aws/aws-sdk-go-v2/service/resourcegroupstaggingapi.(*Client).newRequest(0xc00012a090, 0xc0001306c0, 0x9953c0, 0xc00012c840, 0x97fa20, 0xc00011cb20, 0x60)
	/go/pkg/mod/github.com/aws/aws-sdk-go-v2@v0.20.0/service/resourcegroupstaggingapi/api_client.go:78 +0x195
github.com/aws/aws-sdk-go-v2/service/resourcegroupstaggingapi.(*Client).GetResourcesRequest(0xc00012a090, 0xc00012c840, 0x0, 0x0, 0x1)
	/go/pkg/mod/github.com/aws/aws-sdk-go-v2@v0.20.0/service/resourcegroupstaggingapi/api_op_GetResources.go:202 +0x1d3
main.tagsInterface.get(0xb13640, 0xc00012a090, 0xb1e2a0, 0xc00012a0a0, 0xc000028670, 0x9, 0xc000028658, 0x3, 0x0, 0x0, ...)
	/opt/aws_tags.go:115 +0x218
main.scrapeDiscoveryJobUsingMetricData(0xc000028670, 0x9, 0xc000028658, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc00000cb60, ...)
	/opt/abstract.go:145 +0x1ef
main.scrapeAwsData.func1(0xc000172120, 0xc000200450, 0xc000220240, 0x2, 0x2, 0x0, 0x0, 0x0, 0xc000126a20, 0xc00011c9a0, ...)
	/opt/abstract.go:44 +0x1a0
created by main.scrapeAwsData
	/opt/abstract.go:30 +0x1b7```

**Comment by SerhiiSokolov** [comment]
Hi, any progress here? Can't use YACE with EKS :(

**Comment by lbenedetto** [comment]
I stopped working on this because we got IRSA working by fixing an issue in the Helm chart for yace.

https://github.com/mogaal/helm-charts/pull/2/files

**Comment by thomaspeitz** [comment]
Can be reopened if somebody wants to work on this.

**Pull request closed without merging**
