### PR TITLE
DRAFT: add AWS network Firewall

### PR DESCRIPTION
**Pull request by rhys-evans**
Would close: https://github.com/ivx/yet-another-cloudwatch-exporter/issues/328

### CODE REVIEW

**Comment by rhys-evans** [comment]
At present config file needs to have a section like

```
    awsDimensions:
      - AvailabilityZone
      - Engine
```

added to the scrape job, need to see how to get around this as there is a 4th dimension (CustomAction) that may be available

**Comment by rhys-evans** [comment]
Hi, can anyone explain what this line is doing https://github.com/ivx/yet-another-cloudwatch-exporter/blob/96a3fce22db1385e33aab31bda7dcd524b7e121a/aws_cloudwatch.go#L350 as it stoping us dynamically building the dimension list

**Comment by rhys-evans** [comment]
Essentially need to look up the metrics dimensions and then add it to the query automagically somehow

**Comment by thomaspeitz** [comment]
Will look at this probably next week.

Thanks for your contribution :)

**Comment by thomaspeitz** [comment]
Could you please rebase? :)

**Comment by rhys-evans** [comment]
"Rebased" and updated

**Comment by thomaspeitz** [comment]
Thanks a lot :)

**Pull request merged**
