### PR TITLE
Migrate to get metric data api calls

### PR DESCRIPTION
**Pull request by thomaspeitz**

### CODE REVIEW

**Comment by bheight-Zymergen** [comment]
Anything in specific that I could help with on this PR?

**Comment by thomaspeitz** [comment]
@bheight-Zymergen - Currently not. Just moved in a new flat and do not have much time to tackle this bigger topic. If you are interested in doing it, i can throw my stuff away and review / merge your PR.

**Comment by bheight-Zymergen** [comment]
As it is a blocker for me currently I'll check out your current branch and see what I can do.

**Comment by thomaspeitz** [comment]
Closed in favour of new pr.

**Pull request closed without merging**
