### PR TITLE
Add support NLB. And fixes.

### PR DESCRIPTION
**Pull request by reddoggad**
Hello!

- support NLB

Config:
```  - type: nlb
    regions:
      - eu-central-1
    period: 60
    delay: 120
    nilToZero: true
    metrics:
      - name: UnHealthyHostCount
        statistics: [Maximum]
      - name: HealthyHostCount
        statistics: [Minimum]
 ```
Before: 
```
aws_nlb_info{name="arn:aws:elasticloadbalancing:*******:******:loadbalancer/net/lb-external/*******",tag_Environment="Production",tag_Group="Default",tag_Name="lb-external"} 0
aws_nlb_info{name="arn:aws:elasticloadbalancing:*******:******:loadbalancer/net/lb-internal/********",tag_Environment="Production",tag_Group="Default",tag_Name="lb-internal"} 0
....
```
After:
```
aws_nlb_info{name="arn:aws:elasticloadbalancing:******:******:loadbalancer/net/lb-external/******",tag_Environment="Production",tag_Group="Default",tag_Groups="",tag_Name="lb-external"} 0
aws_nlb_info{name="arn:aws:elasticloadbalancing:******:******:loadbalancer/net/lb-internal/******",tag_Environment="Production",tag_Group="Default",tag_Groups="",tag_Name="lb-internal"} 0
aws_nlb_info{name="arn:aws:elasticloadbalancing:******:******:targetgroup/nginx-int/******",tag_Environment="",tag_Group="Tcp",tag_Groups="Tcp:Default",tag_Name="nginx-int"} 0
aws_nlb_info{name="arn:aws:elasticloadbalancing:******:******:targetgroup/nginx/******",tag_Environment="",tag_Group="Tcp",tag_Groups="Tcp:Default",tag_Name="nginx"} 0
aws_nlb_tg_healthy_host_count_minimum{dimension_LoadBalancer="net/lb-external/******",dimension_TargetGroup="targetgroup/nginx/******",name="arn:aws:elasticloadbalancing:******:******:targetgroup/nginx/******",region="******"} 3
aws_nlb_tg_healthy_host_count_minimum{dimension_LoadBalancer="net/lb-internal/******",dimension_TargetGroup="targetgroup/nginx-int/******",name="arn:aws:elasticloadbalancing:******:******:targetgroup/nginx-int/******",region="******"} 3
aws_nlb_tg_un_healthy_host_count_maximum{dimension_LoadBalancer="net/lb-external/******",dimension_TargetGroup="targetgroup/nginx/******",name="arn:aws:elasticloadbalancing:******:******:targetgroup/nginx/******",region="******"} 0
aws_nlb_tg_un_healthy_host_count_maximum{dimension_LoadBalancer="net/lb-internal/******",dimension_TargetGroup="targetgroup/nginx-int/******",name="arn:aws:elasticloadbalancing:******:******:targetgroup/nginx-int/******",region="******"} 0
...
```

- Error using variable pointer in a loop (duplicate https://github.com/ivx/yet-another-cloudwatch-exporter/pull/236 but fixed without using new variables)
- Fixed incorrect display of alb, nlb info.
For example, before:
```
aws_alb_info{name="arn:aws:elasticloadbalancing:******:******:targetgroup/test/******",tag_Environment="",tag_Group="Other",tag_Groups="Other:Default",tag_Name="test"} 0     # Target group didn't connect to balancers
aws_alb_info{name="arn:aws:elasticloadbalancing:******:******:targetgroup/nginx-int/******",tag_Environment="",tag_Group="Tcp",tag_Groups="Tcp:Default",tag_Name="nginx-int"} 0                 # Target group connected to NLB.
aws_alb_info{name="arn:aws:elasticloadbalancing:******:******:targetgroup/proxy/******",tag_Environment="",tag_Group="Other",tag_Groups="Other:Default",tag_Name="proxy"} 0               # OK
```
After:
```
aws_alb_info{name="arn:aws:elasticloadbalancing:******:******:targetgroup/proxy/******",tag_Environment="",tag_Group="Other",tag_Groups="Other:Default",tag_Name="proxy"} 0
```

### CODE REVIEW

**Comment by gchenuet** [comment]
Hi,
I'm facing this problem too.
Thanks for the PR !

**Comment by singhjagmohan1000** [comment]
This PR needs to be merged and released

**Comment by reddoggad** [comment]
@singhjagmohan1000 Hello. 
Please show example (screenshot for targetGroup in aws ui and metrics aws_nlb_tg_healthy_host_count_minimum).

I'm currently testing in my production aws account and it works correctly.

Thx.

**Comment by thomaspeitz** [comment]
Hey @reddoggad could you please rebase 👍 

Thanks for your contribution, will try to merge and release today.

**Comment by singhjagmohan1000** [comment]
It was giving wrong healthy host count and I had to switch back. Please test and verify before releasing.

**Comment by reddoggad** [comment]
@singhjagmohan1000 please give me your config.

**Comment by thomaspeitz** [comment]
Awesome love it!

**Comment by chadiandianwenrou** [comment]
NLB's UnHealthyHostCount data cannot be scraped




apiVersion: v1
data:
  config.yml: |
    discovery:
      exportedTagsOnMetrics:
        nlb:
          - Department
          - Tier
          - Environment
          - Project
      jobs:
      - type: "nlb"
        regions:
          - cn-north-1
        nilToZero: true
  
        metrics:
          - name: ActiveFlowCount
            statistics: [Average]
            period: 300
            length: 600
          - name: ActiveFlowCount_TCP
            statistics: [Sum]
            period: 300
            length: 600
          - name: UnHealthyHostCount
            statistics: [Maximum]
            period: 300
            length: 600
            aws_dimensions: ["TargetGroup"]
          - name: HealthyHostCount
            statistics: [Minimum]
            period: 300
            length: 600
          - name: TCP_ELB_Reset_Count
            statistics: [Sum]
            period: 300
            length: 600

**Comment by chadiandianwenrou** [comment]
NLB's UnHealthyHostCount data cannot be scraped



`
apiVersion: v1
data:
config.yml: |
discovery:
exportedTagsOnMetrics:
nlb:
- Department
- Tier
- Environment
- Project
jobs:
- type: "nlb"
regions:
- cn-north-1
nilToZero: true

    metrics:
      - name: ActiveFlowCount
        statistics: [Average]
        period: 300
        length: 600
      - name: ActiveFlowCount_TCP
        statistics: [Sum]
        period: 300
        length: 600
      - name: UnHealthyHostCount
        statistics: [Maximum]
        period: 300
        length: 600
        aws_dimensions: ["TargetGroup"]
      - name: HealthyHostCount
        statistics: [Minimum]
        period: 300
        length: 600
      - name: TCP_ELB_Reset_Count
        statistics: [Sum]
        period: 300
        length: 600`

**Comment by chadiandianwenrou** [comment]
apiVersion: v1
data:
config.yml: |
discovery:
exportedTagsOnMetrics:
nlb:
- Department
- Tier
- Environment
- Project
jobs:
- type: "nlb"
regions:
- cn-north-1
nilToZero: true

    metrics:
      - name: ActiveFlowCount
        statistics: [Average]
        period: 300
        length: 600
      - name: ActiveFlowCount_TCP
        statistics: [Sum]
        period: 300
        length: 600
      - name: UnHealthyHostCount
        statistics: [Maximum]
        period: 300
        length: 600
        aws_dimensions: ["TargetGroup"]
      - name: HealthyHostCount
        statistics: [Minimum]
        period: 300
        length: 600
      - name: TCP_ELB_Reset_Count
        statistics: [Sum]
        period: 300
        length: 600``

**Comment by chadiandianwenrou** [comment]
`啊是大啊是大啊是大啊是大as
啊是大
啊是大
啊是大
阿斯顿阿斯顿啊是大
`

**Comment by chadiandianwenrou** [comment]
@thomaspeitz    @singhjagmohan1000   @reddoggad  
this is my config

apiVersion: v1
data:
  config.yml: |
    discovery:
      exportedTagsOnMetrics:
        nlb:
          - Department
          - Tier
          - Environment
          - Project
      jobs:
      - type: "nlb"
        regions:
          - cn-north-1
        nilToZero: true
        metrics:
          - name: UnHealthyHostCount
            statistics: [Maximum]
            period: 60
            delay: 120
          - name: HealthyHostCount
            statistics: [Minimum]
            period: 60
            delay: 120

**Pull request merged**
