### PR TITLE
trimmed resource string which is passed as value in AWS dimensions in case of alb

### PR DESCRIPTION
**Pull request by GeeksWine**

### CODE REVIEW

**Comment by tsupertramp** [comment]
@linefeedse - As you initially added ALB support. Does this PR breaks anything for you?

From my first view it looks good. But as me personally and the company i work for not use ALBs i am afraid to merge.

Greetings, Thomas

**Comment by tsupertramp** [comment]
I will merge this together with the other PR in a new version. @GeeksWine - Sorry for the long delay was hoping we get more input on this.

**Comment by GeeksWine** [comment]
Sure. No problem :)

**Comment by tsupertramp** [comment]
https://github.com/ivx/yet-another-cloudwatch-exporter/issues/42 - Reference PR with Issue.

**Pull request merged**
