### PR TITLE
Added config validation

### PR DESCRIPTION
**Pull request by daviddetorres**
Implements feature requested in #133

### CODE REVIEW

**Comment by thomaspeitz** [comment]
Nice <3 <3 <3 - Could you rebase and i merge?

**Comment by daviddetorres** [comment]
Sure! Let me work on this and see the changes needed and I'll ping you when ready. 
I'll change the name to [WIP] until ready.

**Comment by daviddetorres** [comment]
Hi! 

I made the changes in my branch. Changes should appear in the pull request, but I do not see them yet... 

If I compare now the branch with the upstream, it says that can merge without conflicts... however, here I still see conflicts. 

If this continues, I'll remove this PR and make a fresh new one without conflicts.

**Comment by thomaspeitz** [comment]
@daviddetorres - So is it mergable? - Wanted to release today and would like to have your PR in there.

**Comment by daviddetorres** [comment]
Yes. I just confirmed that the merge is applied and the PR is mergable with no conflicts to resolve 🤓

**Pull request merged**
