### PR TITLE
Add support for specifying an External ID value in IAM role ARNs.

### PR DESCRIPTION
**Pull request by cristiangreco**
This is a breaking change as it requires the YAML config file to be
updated if you're currently using the `roleArns` field.

**Context**
IAM role delegation allows optionally setting an External ID string
value shared between parties. This is useful and recommended in order to
prevent the "confused deputy" problem when the account that can assume
the IAM role is outside your organisation.
When an External ID is setup for a role, users in the trusted account
must provide the exact identifier value to be able to assume the role.

More context here: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user_externalid.html

**Changes**
In this PR we change the config file format to allow specifying IAM
roles with both an ARN string and an External ID string. The credentials
handling code is updated to check for the presence of the External ID
value and pass it along in the assumeRole request, if present.

### CODE REVIEW

**Comment by cristiangreco** [comment]
Hey @thomaspeitz 👋 

I was wondering if you had a chance to look at this PR. Let me know if you have any feedback or need any change/clarification.

Thanks! 🙏

**Comment by thomaspeitz** [comment]
Hey @cristiangreco sorry that I was not able to put this into newest release. That was mainly due to the size.

Need to read it carefully. I overflew it and it looked good but need more time :)

Thanks for submitting this! Really appreciate it!

**Comment by cristiangreco** [comment]
Thank you very much for your prompt reply @thomaspeitz! No rush, just wanted to check if there's any big blocker that would stop getting this merged after proper review. I'll rebase the PR in the meanwhile.

Feel free to ping me for anything.

**Comment by cristiangreco** [comment]
Hey @thomaspeitz 👋 sorry to bother you, hope you're doing great!

Have you had any chance to look at this PR recently? I'm available for any clarification or help you might need.

**Comment by cristiangreco** [comment]
Hi @thomaspeitz, pinging you as I see there's been some recent activity in the repo ☺️

I've just rebased this PR. We've been using these changes in production for a while now, would be great to have them merged.

If you need any help with repo maintenance, generally speaking, I'm also available to help you with other PRs and bugs. Let me know and we could schedule a chat ;)

**Comment by thomaspeitz** [comment]
Yeah, I am planning to reorganize this whole project in august and take more time for it.

I put you on my list and will contact you! - Just send me a mail yace@nerdswords.de for your contact details! - Thanks <3

**Comment by cristiangreco** [comment]
Thank you very much @thomaspeitz! I'll email you today.

While at it, I've rebased this other tiny bugfix PR as well 🙂 https://github.com/ivx/yet-another-cloudwatch-exporter/pull/375

**Pull request merged**
