### PR TITLE
Add optional structured logging

### PR DESCRIPTION
**Pull request by bheight-Zymergen**
- Adds sirupsen/logrus as the logging formatter
- Adds optional structured logging configurable through a flag. 
- Sets the default as the TextFormatter to maintain backwards compatibility
- Adds the ability to set log output as structured json.

### CODE REVIEW

**Comment by thomaspeitz** [comment]
Will try to release this on Friday. Can not guarantee as i need help. Currently one handed till surgery heals.

**Comment by bheight-Zymergen** [comment]
No rush on this at all -- get better @thomaspeitz !

**Comment by thomaspeitz** [comment]
Hey @bheight-Zymergen - PR looks good to me. I would suggest let us make json logging default and not allow to configure it into different formats. This reduces complexity a little bit :) No need for ascii anymore.

**Comment by bheight-Zymergen** [comment]
Yeah, I'll update the PR

**Comment by bheight-Zymergen** [comment]
@thomaspeitz Pushed in the changes, and also found a bad indent that got merged in that is fixed in this PR as well.

**Comment by thomaspeitz** [comment]
Thanks a lot :) <3

**Pull request merged**
